version: "2"
services:
  flask:
    build: 
      context: ../..
      dockerfile: ../web/Dockerfile
    volumes:
      - "../../src:/project/src"

  postgres:
    build: 
      context: .
      dockerfile: ../postgres/Dockerfile
    ports:
      - "5432:5432"
    env_file:
      - ./config.env
    
