version: "2"
services:
  flask:
    extends:
      file: ./base.yml
      service: flask
    ports:
      - "5000:5000"
    environment:
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
      - FLASK_DEBUG=0
    depends_on:
      - postgres

  postgres:
    extends:
      file: ./base.yml
      service: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata

volumes:
  pgdata:
