version: "2"
services:
  web:
    image: grihabor/testing-server
    build: 
      context: ../..
      dockerfile: docker/dev/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PYTHONPATH=/project/src
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
      - FLASK_DEBUG=0
    env_file:
      - ./config.env
    volumes:
      - ~/Projects/testing-server/src:/project/src
    depends_on:
      - postgres

  postgres:
    image: library/postgres:9.6-alpine
    ports:
      - "5432:5432"
    env_file:
      - ./config.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata

volumes:
  pgdata:
