version: "2"
services:
  flask:
    extends:
      file: ./base.yml
      service: flask
    env_file:
      - ./config.env
    ports:
      - "5000:5000"
    environment:
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
      - FLASK_DEBUG=1
    depends_on:
      - postgres
    volumes:
      - keys:/project/keys

  postgres:
    extends:
      file: ./base.yml
      service: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata

  worker:
    build:
      context: ../..
      dockerfile: docker/dev/worker/Dockerfile
    depends_on:
      - rabbitmq
      - postgres
    env_file:
      - ./config.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  rabbitmq:
    env_file:
      - ./config.env
    image: library/rabbitmq:3-alpine
    ports:
      - "5672"
    environment:
      - RABBITMQ_VM_MEMORY_HIGH_WATERMARK=100mb

volumes:
  pgdata:
  keys:
