version: "2"
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_DEBUG=1
      - PYTHONPATH=/project/src
    volumes:
      - ~/Projects/testing-server/src:/project/src
    depends_on:
      - postgres

  postgres:
    image: library/postgres:9.6-alpine
    env_file:
      - ./database.env
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata

volumes:
  pgdata:
