version: "2"
services:
  bash:
    extends:
      file: ../dev/base.yml
      service: flask
    command: /bin/sh
    networks:
      - default

networks:
  default:
    external:
      name: dev_default
