version: "2"
services:

  rabbitmq:
    image: library/rabbitmq:3-alpine
    ports:
      - "5672"
      
  worker:
    image: tesver/worker:latest
    build:
      context: ..
      dockerfile: docker/services/worker/Dockerfile
  
  postgres:
    image: tesver/postgres:latest
    build: 
      context: .
      dockerfile: services/postgres/Dockerfile
      
  gunicorn:
    image: tesver/gunicorn:latest
    build:
      context: ..
      dockerfile: docker/services/gunicorn/Dockerfile

  flask:
    image: tesver/flask:latest
    build:
      context: ..
      dockerfile: docker/services/flask/Dockerfile
