"""empty message

Revision ID: 7c9c5415d5fb
Revises: 899e20eba205
Create Date: 2017-09-11 12:40:31.142472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c9c5415d5fb'
down_revision = '899e20eba205'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
