"""empty message

Revision ID: 91505ebe2eb7
Revises: 7c9c5415d5fb
Create Date: 2017-09-11 12:41:27.426784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91505ebe2eb7'
down_revision = '7c9c5415d5fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active_repository_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'active_repository_id')
    # ### end Alembic commands ###
