version: "2"
services:
  gunicorn:
    extends:
      file: ./base.yml
      service: gunicorn
    environment:
      - FLASK_DEBUG=0
    depends_on:
      - postgres
    volumes:
      - keys:/project/keys

  worker:
    extends:
      file: ../build.yml
      service: worker
    depends_on:
      - postgres
      - rabbitmq
    env_file:
      - ./config.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - keys:/project/keys
      
  rabbitmq:
    extends: 
      file: ../build.yml
      service: rabbitmq
    env_file:
      - ./config.env
    
  postgres:
    extends:
      file: ../build.yml
      service: postgres
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - ./config.env
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata

  nginx:
    build:
      context: .
      dockerfile: ../nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - gunicorn

volumes:
  pgdata:
  keys:
