version: "2"
services:
  gunicorn:
    extends:
      file: ../build.yml
      service: gunicorn
    depends_on:
      - postgres
    volumes:
      - tesver_stage_keys:/project/keys
    env_file:
      - ./config.env
    ports:
      - "80:5000"

  worker:
    extends:
      file: ../build.yml
      service: worker
    depends_on:
      - postgres
      - rabbitmq
    env_file:
      - ./config.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - tesver_stage_keys:/project/keys
      
  rabbitmq:
    extends: 
      file: ../build.yml
      service: rabbitmq
    env_file:
      - ./config.env
    
  postgres:
    extends:
      file: ../build.yml
      service: postgres
    ports:
      - "5432"
    env_file:
      - ./config.env
    volumes:
      - tesver_stage_pgdata:/var/lib/postgresql/data/pgdata

volumes:
  tesver_stage_pgdata:
    external: true
  tesver_stage_keys:
    external: true
  tesver_stage_logs:
    external: true
  tesver_stage_results:
    external: true
